# Generated by Django 2.2.17 on 2021-04-18 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_images/faculty/')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_faculties', to='AdminUser.AdminProfile')),
            ],
        ),
    ]
