# Generated by Django 2.2.17 on 2021-05-05 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyUser', '0002_facultyprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_faculties', to='AdminUser.AdminProfile'),
        ),
    ]
