# Generated by Django 2.2.17 on 2021-05-05 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyUser', '0003_auto_20210505_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='invite_sent',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='joined',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
