# Generated by Django 2.2.17 on 2021-05-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyUser', '0004_auto_20210505_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='joined',
            field=models.DateField(null=True),
        ),
    ]
