# Generated by Django 2.2.17 on 2021-05-05 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyUser', '0006_facultyprofile_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyprofile',
            name='uuid',
        ),
    ]
