# Generated by Django 2.2.17 on 2021-05-06 13:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUser', '0004_adminprofile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
