# Generated by Django 2.2.17 on 2021-04-30 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StudentUser', '0003_auto_20210430_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='joined',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
