# Generated by Django 2.2.17 on 2021-04-25 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210422_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
