# Generated by Django 2.2.17 on 2021-01-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_adminprofile_facultyprofile_schedule_slot_slotinfo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together=set(),
        ),
    ]
