# Generated by Django 2.2.17 on 2021-01-24 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210110_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotinfo',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_slots', to='base.Schedule'),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_followed', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Schedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.StudentProfile')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='students',
            field=models.ManyToManyField(through='base.StudentData', to='base.StudentProfile'),
        ),
    ]
