# Generated by Django 2.2.17 on 2021-05-06 13:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210506_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
