# Generated by Django 2.2.17 on 2021-01-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_facultyprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_images/admin/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_images/student/'),
        ),
    ]
