# Generated by Django 2.2.17 on 2021-01-27 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210127_1206'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facultyprofile',
            unique_together={('name', 'admin')},
        ),
    ]
